data:
  class_path: anomalib.data.MVTec
  init_args:
    root: /data/users/cugwu/ad_data/mvtec
    category: bottle
    train_batch_size: 16
    eval_batch_size: 32
    num_workers: 8
    task: segmentation
    image_size:
    - 256
    - 256
    transform: null
    train_transform: null
    eval_transform: null
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    seed: null
model:
  class_path: anomalib.models.ReverseDistillation
  init_args:
    backbone: wide_resnet50_2
    layers:
    - layer1
    - layer2
    - layer3
    anomaly_map_mode: ADD
    pre_trained: true
normalization:
  normalization_method: min_max
metrics:
  image:
  - AUROC
  pixel:
  - AUPRO
  - AUROC
  threshold:
    class_path: anomalib.metrics.F1AdaptiveThreshold
    init_args:
      default_value: 0.5
#visualization:
#  visualizers: null
#  save: true
#  log: true
#  show: false
logging:
  log_graph: false
seed_everything: true
task: segmentation
#results_dir:
#  path: /data/users/cugwu/ad_data/results/F4AD/imagenet
#  unique: false
ckpt_path: null
trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 32
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 200
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  overfit_batches: 0.0
  val_check_interval: 1.0
  check_val_every_n_epoch: 200
  num_sanity_val_steps: 0
  log_every_n_steps: 50
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  deterministic: false
  benchmark: false
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
